export enum PitAction {
  CHECKOUT = 'checkout',
  CHECKOUT_ALIAS = 'co',
  CHECKOUT_DEVELOP = 'cod',
  CHECKOUT_MASTER = 'com',
  REVIEW = 'review',
  REVIEW_ALIAS = 'rv',
  CLEAN = 'clean',
  CLEAN_ALIAS = 'cl',
  PULL_ORIGIN = 'pulo',
  PULL_ORIGIN_REBASE = 'pulor',
  DOCKER = 'docker',
  DOCKER_ALIAS = 'd',
  JIRA = 'jira',
  USER = 'user',
  HELP = 'help',
  HELP_ALIAS1 = '--help',
  HELP_ALIAS2 = 'h',
  HELP_ALIAS3 = '-h',
  DEBUG = 'debug',
}
