name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Code check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Check code format
        run: npm run format:check

      - name: Lint all code
        run: npm run lint

      - name: Build app
        run: npm run build
